### ISSUE TITLE
Support resizing luks root

### ISSUE THREAD

**Issue by sedlund** [coreos/fedora-coreos-config#1444]
I didnt see this documented as a limitation, but ignition fails with

`ignition-ostree-growfs 'nothing to read on input'`

Seems to come from:  https://github.com/coreos/fedora-coreos-config/blob/532fd714e4fff8ee6f6f77cd09f4889560512299/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-growfs.sh#L88

Here is an ignition

```yaml
variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      password_hash: $6$ub
      ssh_authorized_keys:
        - ssh-rsa AAAAB3Nz

boot_device:
  luks:
    tpm2: true

storage:

  disks:
    - device: /dev/nvme0n1
      partitions:
        - label: ceph
          # 12G + 1 MiB for the partition table, 384 for `/boot`, 127 for `/boot/efi`
          start_mib: 12801
          size_mib: 0

  filesystems:
    - device: /dev/mapper/root
      format: btrfs
      label: root
      mount_options:
        - compress=zstd:1
      wipe_filesystem: true
```
